development:
  adapter: postgresql
  encoding: unicode
  database: bootcamp-api
  pool: 5
  username: postgres
  password: 123456
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: bootcamp-api
  pool: 5
  username: postgres
  password: 123456
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: bootcamp_yicw
  pool: 5
  username: bootcamp
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>